channels:
  - conda-forge
dependencies:
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - hypothesis
  - numba
  - numpy
  - healpy
  - geopandas
  - pandas
  - xarray
  - folium
  - shapely
