channels:
  - conda-forge
dependencies:
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - hypothesis
  - numpy
  - dask
  - geopandas
  - pandas
  - sparse
  - xarray
  - folium
  - shapely
  - opt_einsum
  - matplotlib
  - pip
  - pip:
      - xdggs
      - cdshealpix
      - healpix-geo
