channels:
  - conda-forge
dependencies:
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - hypothesis
  - numpy
  - dask
  - sparse
  - xarray
  - opt_einsum
  - matplotlib-base
  - xdggs
  - cdshealpix
  - pip
  - pip:
      - healpix-geo
