name: healpix-indexing-tests
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - numba
  - numpy
  - healpy
  - geopandas
  - pandas
  - xarray
  - folium
  - shapely
